"""Project-wide constants for TeamFinder."""

AVATAR_COLORS = (
    "#6B7280",
    "#4B5563",
    "#2563EB",
    "#047857",
    "#7C3AED",
    "#B45309",
)
AVATAR_FONT_SIZE = 120
AVATAR_SIZE = 256
AVATAR_VERTICAL_SHIFT = 8

NAME_MAX_LENGTH = 124
PHONE_MAX_LENGTH = 12
ABOUT_MAX_LENGTH = 256

PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_OPEN = "open"
PROJECT_STATUS_CLOSED = "closed"
PROJECT_STATUS_CHOICES = (
    (PROJECT_STATUS_OPEN, "Открыт"),
    (PROJECT_STATUS_CLOSED, "Закрыт"),
)
PROJECT_STATUS_MAX_LENGTH = max(
    len(status) for status, _ in PROJECT_STATUS_CHOICES
)

SKILL_NAME_MAX_LENGTH = 124
SKILL_SUGGEST_LIMIT = 10

ITEMS_PER_PAGE = 12

HTTP_ERROR_STATUS = "error"
HTTP_OK_STATUS = "ok"
